version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php app.php'
  relay: pipes

status:
  address: '127.0.0.1:2114'
  unavailable_status_code: 500

http:
  address: '0.0.0.0:8000'
  middleware:
    - gzip
    - headers
  headers:
    cors:
      allowed_origin: ${RR_CORS_ALLOWED_ORIGIN:-*}
      allowed_headers: ${RR_CORS_ALLOWED_HEADERS:-*}
      allowed_methods: ${RR_CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE}
      allow_credentials: false
      exposed_headers: ${RR_CORS_EXPOSED_HEADERS:-Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,Content-Disposition,X-RateLimit-Remaining,X-RateLimit-Retry-After,X-RateLimit-Limit,X-Captcha}
      max_age: 600
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100

jobs:
  pool:
    num_workers: 4
    max_worker_memory: 100
  consume: { }

kv:
  local:
    driver: memory
    config:
      interval: 60

centrifuge:
  proxy_address: ${RR_CENTRIFUGE_PROXY_ADDRESS:-tcp://0.0.0.0:10001}
  grpc_api_address: ${RR_CENTRIFUGE_GRPC_API_ADDRESS}
  poll:
    num_workers: ${RR_CENTRIFUGE_NUM_WORKERS:-4}
