version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php app.php'
  relay: pipes

status:
  address: '127.0.0.1:2114'
  unavailable_status_code: 500

http:
  address: '0.0.0.0:8000'
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100

jobs:
  pool:
    num_workers: 4
    max_worker_memory: 100
  consume: { }

kv:
  local:
    driver: memory
    config:
      interval: 60

centrifuge:
  proxy_address: ${RR_CENTRIFUGE_PROXY_ADDRESS:-tcp://0.0.0.0:10001}
  grpc_api_address: ${RR_CENTRIFUGE_GRPC_API_ADDRESS}
  poll:
    num_workers: ${RR_CENTRIFUGE_NUM_WORKERS:-4}
