version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

server:
  command: 'php app.php'
  relay: pipes

http:
  address: '127.0.0.1:8000'
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100

jobs:
  pool:
    num_workers: 4
    max_worker_memory: 100
  consume: { }

kv:
  local:
    driver: memory
    config:
      interval: 60
